name: astro_refresh_indicator
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^2.0.0
  rive: ^0.7.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.3.0

flutter:
  assets:
    - assets/space_reload.riv