name: astro_refresh_indicator
version: 1.0.0
description: A space refresh indicator for flutter.
homepage: https://github.com/Ilya-Korolev/astro_refresh_indicator
repository: https://github.com/Ilya-Korolev/astro_refresh_indicator
documentation: https://github.com/Ilya-Korolev/astro_refresh_indicator
issue_tracker: https://github.com/Ilya-Korolev/astro_refresh_indicator/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  pull_to_refresh: ^2.0.0
  rive: ^0.7.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^2.3.0

flutter:
  assets:
    - assets/space_reload.riv